#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage:"
    echo "questions [url]"
else
    curl $1 | \
        pandoc -f html -t plain | \
        #tr '\n' ' ' | \
        #tr '\?\ ' '\?\n' | \
        grep [A-Z].*\?
fi    
